import requests
import base64
import os

def create_repo_and_push(email: str, task: str, round_num: int, nonce: str, brief: str) -> str:
    """
    Creates a new GitHub repo under your account and uploads a README file.
    Returns the repository URL.
    """
    github_token = os.getenv("GITHUB_TOKEN")
    github_username = os.getenv("GITHUB_USERNAME")

    if not github_token or not github_username:
        raise ValueError("Missing GITHUB_TOKEN or GITHUB_USERNAME in .env file")

    repo_name = f"{email.replace('@', '_').replace('.', '_')}_round{round_num}_{nonce}"

    # 1. Create repository
    create_repo_url = "https://api.github.com/user/repos"
    repo_data = {"name": repo_name, "private": False}
    headers = {"Authorization": f"token {github_token}"}
    res = requests.post(create_repo_url, json=repo_data, headers=headers)

    if res.status_code not in [200, 201]:
        raise Exception(f"Error creating repo: {res.text}")

    repo_url = res.json()["html_url"]

    # 2. Add README.md
    content = f"# {task}\n\n{brief}\n\nAuto-generated by AI Autograder."
    content_b64 = base64.b64encode(content.encode()).decode()
    file_url = f"https://api.github.com/repos/{github_username}/{repo_name}/contents/README.md"

    file_data = {
        "message": "Initial commit from AI Autograder",
        "content": content_b64
    }

    res = requests.put(file_url, json=file_data, headers=headers)
    if res.status_code not in [200, 201]:
        raise Exception(f"Error creating README.md: {res.text}")

    return repo_url
