import os
import json
from dotenv import load_dotenv
import httpx
import asyncio

load_dotenv()

AIPIPE_API_KEY = os.getenv("AIPIPE_API_KEY")
if not AIPIPE_API_KEY:
    raise ValueError("AIPIPE_API_KEY not found in environment variables")

BASE_URL = "https://aipipe.org/openai/v1"  # Using OpenAI proxy via Aipipe


async def generate_app_code(task: str, model: str = "gpt-4.1-nano", save_files: bool = False):
    """
    Generate minimal HTML+JS app and README using Aipipe API.

    Args:
        task: Description of the app/task to generate.
        model: Model to use (e.g., 'gpt-4.1-nano', 'gemini-2.0-flash-lite-001').
        save_files: If True, saves `index.html` and `README.md` locally.

    Returns:
        app_code (str), readme (str)
    """
    headers = {
        "Authorization": f"Bearer {AIPIPE_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": model,
        "input": f"Generate minimal HTML+JS app and README for this task:\n\n{task}"
    }

    async with httpx.AsyncClient(timeout=60) as client:
        try:
            response = await client.post(f"{BASE_URL}/responses", headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()

            # Extract text output
            output_text = ""
            if "output" in data and len(data["output"]) > 0:
                content_list = data["output"][0].get("content", [])
                for c in content_list:
                    if "text" in c:
                        output_text += c["text"]

            # Split into app code and README
            parts = output_text.split("README:", 1)
            app_code = parts[0].strip()
            readme = parts[1].strip() if len(parts) > 1 else "Generated by AI"

            # Save files if requested
            if save_files:
                with open("index.html", "w", encoding="utf-8") as f:
                    f.write(app_code)
                with open("README.md", "w", encoding="utf-8") as f:
                    f.write(readme)

            return app_code, readme

        except httpx.HTTPStatusError as e:
            return "", f"Error calling Aipipe API: {e.response.status_code} - {e.response.text}"
        except Exception as e:
            return "", f"Network or parsing error: {str(e)}"


# Example test run
if __name__ == "__main__":
    async def test():
        app_code, readme = await generate_app_code("Build a simple todo list app", save_files=True)
        print("App code:\n", app_code[:300], "...\n")  # print first 300 chars
        print("README:\n", readme[:300], "...")  # print first 300 chars

    asyncio.run(test())
